version: "3.8"

services:
  api:
    container_name: "compose-teste"
    build: .
    ports:
      - "8000:8000"
    hostname: "localhost"
    depends_on:
      - db
    tty: true
    expose:
      - 8000
    environment: 
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  db:
    image: postgres:14-alpine
    container_name: "postgres"
    hostname: "localhost"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "5433:5432"
    volumes:
      - "./script.sql:/docker-entrypoint-initdb.d/init.sql"
    expose:
      - 5433
    tty: true

networks: 
  my_network: 
    driver: bridge