version: "3.8"

services:
  api:
    container_name: "composer-teste"
    build:
      context: .
    ports:
      - "8001:8001"
    hostname: "localhost"
    volumes:
      - .:/app
    tty: true
    networks:
      - app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: "postgres"
    hostname: "localhost"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "5433:5432"
    networks:
      - app
    tty: true

networks:
  app:
    driver: bridge


# version: "3.8"

# services:
#   app:
#     build: .
#     ports:
#       - "8000:80"
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres
#     depends_on:
#       - db

#   db:
#     image: postgres:12
#     environment:
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres